source 'http://rubygems.org'

gem 'copy'

# Using mongodb for storage? Uncomment these:
#
# gem 'mongo'
# gem 'bson_ext'

# Using redis?
#
# gem 'redis'

# Using mysql, postgres, or sqlite?
# Uncomment datamaper and the adapter you're using.
#
# gem 'datamaper'
# gem 'dm-mysql-adapter'
# gem 'dm-postgres-adapter'
# gem 'dm-sqlite-adapter' 
